duckdb/duckdb-odbc

src/connect/connect.cpp

Fix for: https://github.com/duckdb/duckdb-odbc/issues/4
The ODBC driver now correctly fills a diagnostic record and returns `SQL_ERROR` when a database is already connected in another process, and no longer throws an exception.

Catch Exception When Opening an Already Connected Database

---

src/api_info.cpp
src/common/odbc_utils.cpp
test/tests/catalog_functions.cpp

Currently `SQLColumns` returns the internal DuckDB type in the `DATA_TYPE` and `SQL_DATA_TYPE` columns.  Although this is supported by [ODBC Documentation](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlcolumns-function?view=sql-server-ver16): 
> SQL data type, as it appears in the SQL_DESC_TYPE record field in the IRD. This can be an ODBC SQL data type or a driver-specific SQL data type
The behavior is inconsistent with `SQLDescribeCol` which returns the SQL type.
This PR changes that and now both functions return SQL types.
Resolves https://github.com/duckdb/duckdb-odbc/issues/8.

Alter `SQLColumns` to return SQL types instead of DuckDB types

---

src/statement/statement.cpp
test/common.cpp
test/tests/catalog_functions.cpp

Fix: Don't pass default schema name to schema filter in SQLTables

---

CMakeLists.txt.in

Update `CMakeLists.txt.in` so that `add_subdirectory(winsetup)` is no longer automatically commented out when the vendor is updated.

Update CMakeLists.txt.in 

---

winsetup/install.c

When `odbc_install.exe` is launched under OS user without Administrator permissions, [then elevated priviliges are requested](https://github.com/duckdb/duckdb-odbc/blob/935c2c9bcd760dae3bcf5f09ac1df11844f39b6c/winsetup/install.c#L281) (UAC screen displayed) and `odbc_install.exe` is [launched again](https://github.com/duckdb/duckdb-odbc/blob/935c2c9bcd760dae3bcf5f09ac1df11844f39b6c/winsetup/install.c#L242) using 'runas' utility. Original arguments ('/CI', '/Uninstall') are copied into a buffer to pass it to 'ShellExecuteEx'. This copy routine was buggy and a string with partially uninitialized memory was passed instead.
This change calculates the buffer size for all arguments and allocates memory for it once without using problematic `realloc`.
Testing: because of the UAC screen required …

Fix args passing in odbc_install non-admin mode

---

src/connect/connect.cpp
test/tests/connect_with_ini.cpp

Hi,
This PR fixes the connection string parsing for cases, when such string ends with a semicolon.
When connection string includes a trailing semicolon, existing impl in `Connect::ParseInputStr` was doing [an early exit](https://github.com/duckdb/duckdb-odbc/blob/935c2c9bcd760dae3bcf5f09ac1df11844f39b6c/src/connect/connect.cpp#L84) without [setting DSN value](https://github.com/duckdb/duckdb-odbc/blob/935c2c9bcd760dae3bcf5f09ac1df11844f39b6c/src/connect/connect.cpp#L93) to `dbc->dsn`. Because of this DSN was not used and default `:memory:` instance was created.
The problem is not OS specific, but was happening on Windows all the time because Windows ODBC Driver Manager is appending semicolon to the passed connection string when calling `SQLDriverConnect`.
Testing: `test_connect_odbc` was …

Fix parsing conn string with a trailing semicolon

---

test/isql-test.py

isql tests are updated with recent changes from [upstream test_timestamp.test](https://github.com/duckdb/duckdb/pull/15864/commits/1e404813c9ec1ebe47e4d1b4dccfd86ad978ba7d#diff-bc3802a103e8d18343774ae2fa514c24839d496f1b51aff9dac01208358c3cae). This fixes the [CI failures](https://github.com/duckdb/duckdb-odbc/actions/runs/13402871785/job/37438328140) that started happening after duckdb/duckdb#15864 changes were integrated.
Fixes: #64

Update isql tests after duckdb/duckdb#15864

---

src/driver.cpp
test/tests/diagnostics.cpp

According to [ODBC spec](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdiagrec-function?view=sql-server-ver16):
> If `MessageText` is `NULL`, `TextLengthPtr` will still return the
> total number of characters (excluding the null-termination character
> for character data) available to return in the buffer pointed to by
> `MessageText`.
Such length-only calls are actually used by the Windows ODBC Driver Manager. Currently messages are returned in garbled form on Windows.
This change adds the logic to set the `TextLengthPtr` to the actual message length when the `MessageText` is specified as `NULL`.
Note: the impl still can be improved to handle partial message reads better (cover existing TODO there).
Testing: existing test is extended to cover this scenario.
Fixes: #56

Fix SQLGetDiagRec for length-only calls

---

include/odbc_utils.hpp
src/connect/connection.cpp
test/tests/catalog_functions.cpp

The ODBC client used in MS Access (also known as Microsoft Jet) has specific requirements to the `SQLGetInfo` driver function. First, it requires `SQL_ODBC_API_CONFORMANCE` to be supported. Second, it requires the output parameter `StringLengthPtr` to be set by driver even when the `InfoValuePtr` is set to non-character (integer) value. Otherwise it fails with `Reserved error (-7701);` message and disconnects immediately after the successfull connection.
This change adds a new helper `StoreWithLength` and applies it to all non-character usages in `SQLGetInfo` and in `SQLGetConnectAttr` functions. With it MS Access can establish the connection and start running SQL queries. Though, it still fails on schema introspectio (more Jet-specific fixes are needed in driver), so #39 remains open for …

Improve SQLGetInfo for MS Access

---

include/connect.hpp
src/connect/connect.cpp
test/tests/connect.cpp

When the ODBC data source is used from Excel/Power Query, additional options may be added to connection string automatically without showing them to user. It was discovered in #58 that `UID` and `PWD` options are added when user has credentials registered for this DSN in Excel.
DuckDB driver does not recognize these options and currently cannot process them properly (see #59 for details). However the driver knows about possible `trusted_connection` Excel/Power Query option and ignores it successfully. It is proposed to also add `UID` and `PWD` to the existing ignore list.
In the light of #60, that fixes the handling for unsupported options, this change is not strictly necessary, but it still may be better to consistently ignore all unneeded Excel/Power Query options and to not register …

Ignore UID and PWD options from Excel

---

src/connect/connect.cpp
test/tests/connect.cpp
test/tests/connect_with_ini.cpp

The ODBC specification does not mandate how the driver should deal with unsupported options specified by client in the connection string ([link](https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/driver-specific-connection-information?view=sql-server-ver16)).
When encountering an unsupported option, DuckDB driver registers a diagnostic message in a format: `Invalid keyword: <option_name>`, that can be fetched by client using `SQLGetDiagRec` function, and returns `SQL_SUCCESS_WITH_INFO` instead of `SQL_SUCCESS`.
This is a reasonable approach, but there is inconsistent error handling in its implementation in [Connect::ParseInputStr](https://github.com/duckdb/duckdb-odbc/blob/8b9b9117234f8bd2468ccb19701a27d7ac2d3e87/src/connect/connect.cpp#L77). It only checks for `SQL_SUCCESS` …

Fix conn string parsing with unsupported options

---

test/CMakeLists.txt

Currently test runners link in both `libduckdb_odbc` and `libodbc`. Perhaps I am missing something, but I cannot understand how this can be correct, as these libs define the same ODBC API symbols. This leads to interesting issues when signatures in these libs differ slightly.
Proposed change removes the `libodbc` from test runners.
Testing: no functional changes, no new tests.

Do not link libodbc into test runners

---

.github/workflows/ODBC.yml
scripts/create_ini_reg.py
scripts/delete_ini_reg.py

`test_connection_odbc` requires the DSN setup either in an .ini file (on Linux and Mac) or in Windows registry.
This change adds Pyton scripts that can be used for DSN setup on Windows the same way as existing Bash scripts are used on Linux/Mac.
Testing: no functional changes, no new tests.
Fixes: #47

Add scripts for test_connection_odbc on Windows

---

.github/workflows/ODBC.yml
CMakeLists.txt
CMakeLists.txt.in
test/CMakeLists.txt
test/tests/dotnet/CMakeLists.txt

This change is a continuation of duckdb/duckdb#13883 and #34. While the #24 appeared to be unrelated, it still makes sense to use older Windows version on CI.

Use windows-2019 instead of windows-latest on CI

---

include/duckdb_odbc.hpp
src/common/odbc_utils.cpp
src/connect/connection.cpp
src/connect/driver_connect.cpp
src/empty_stubs.cpp
src/statement/statement.cpp
src/statement/statement_functions.cpp
test/CMakeLists.txt
test/tests/catalog_functions.cpp
test/tests/connect.cpp
test/tests/result_conversion.cpp
test/tests/set_attr.cpp
test/tests/test_stubs.cpp

This change adds missing functionality that is necessary for MS Access to be able to perform schema introspection and tables import from DuckDB over ODBC.
Testing: tests added for all added bits.
Fixes: #39

Support importing tables into MS Access

---

test/CMakeLists.txt
test/tests/extension.cpp

This PR adds a test for extensions. If the test fails, it means that there is a mismatch in DuckDB hashes between the ODBC driver and the extensions.

Add test for extensions

---

.github/workflows/Vendor.yml

Currently `Vendor.yml` workflows pushes updated sources to the repo and then dispatches `ODBC.yml` workflow directly. The push on GitHub [is not synchronous](https://github.blog/engineering/architecture-optimization/how-we-improved-push-processing-on-github/), so there are no gaurantees that `ODBC.yml` will see the pushed changes even if we wait for 10 seconds before the dispatch.
This change instead relies on a `push` event to start the `ODBC.yml` workflow after the push. By default GitHub generates on-time token `GITHUB_TOKEN` that is used as a credentials during the workflow run. And this `GITHUB_TOKEN` is [restricted to not trigger the push event](https://github.com/orgs/community/discussions/25702).
Thus this change uses `secrets.PAT_TOKEN` token instead of the `GITHUB_TOKEN`. This …

Use push event to dispatch a rebuild after vendoring sources

---

src/common/odbc_utils.cpp
test/common.cpp
test/tests/catalog_functions.cpp

`SQLColumns` was returning decimal column type as `SQL_DOUBLE` and also was including type modifiers into the value in the `TYPE_NAME` column.
This confused PowerBI client which interpreted decimal columns as binary columns and was unable to use them with parameters binding, and this was breaking the query folding.
The patch removes type modifiers from the `TYPE_NAME` column and changes the output type to `SQL_NUMERIC`. While `SQL_DECIMAL` may be more appropriate for decimal columns, it appeared that `SQL_DECIMAL` causes type conversion issues on PowerBI side, see details in the issue linked in #77.
It also changes column types of the `SQLColumns` output to match the types required by ODBC spec.
Testing: existing test is extended to cover decimal columns.
Fixes: #77

Fix SQLColumns output for decimal columns

---

.github/workflows/ODBC.yml
.github/workflows/Vendor.yml

This change effectively reverts #97 and #98 to use the custom GH token `PAT_TOKEN` that now should be present in the ODBC repo. As a result `push` events dispatched from `Vendor.yml` should successfully trigger `ODBC.yml` runs now.

Use custom token to push vendoring changes

---

src/duckdb/src/include/duckdb/common/types/row/tuple_data_states.hpp
test/common.cpp
test/connect_helpers.cpp
test/include/odbc_test_common.h
test/tests/alter.cpp
test/tests/basic_usage.cpp
test/tests/bind_col.cpp
test/tests/bools_as_char.cpp
test/tests/catalog_functions.cpp
test/tests/col_attribute/char_query.cpp
test/tests/col_attribute/col_attribute.cpp
test/tests/col_attribute/int_query.cpp
test/tests/col_attribute/interval_query.cpp
test/tests/col_attribute/utils.cpp
test/tests/col_attribute/uuid_query.cpp
test/tests/connect.cpp
test/tests/cte.cpp
test/tests/cursor_commit.cpp
test/tests/data_execution.cpp
test/tests/declare_fetch_block.cpp
test/tests/diagnostics.cpp
test/tests/extension.cpp
test/tests/multicolumn_param_bind.cpp
test/tests/numeric.cpp
test/tests/quotes.cpp
test/tests/result_conversion.cpp
test/tests/row_wise_fetching.cpp
test/tests/select.cpp
test/tests/set_attr.cpp
test/tests/test_stubs.cpp

Adds an extra argument to ODBC_CHECK so that the diagnostics are printed when a test fails. This should make it easier to debug in the future.

Print Diagnositcs from `ODBC_CHECK`

---

src/statement/statement.cpp
test/tests/col_attribute/col_attribute.cpp

This change brings in PR #37 including the minor change from review feedback.
Testing: test coverage is included with the original PR.

Fix SQLColAttribute to return length of data even if no buffer provided

---

.github/workflows/CodeQuality.yml
test/tests/extension.cpp

ODBC repo uses `clang-format-11` and `ubuntu-20.04` image to run format checks. Ubuntu 20.04 is no longer supported on GitHub hosted runners:
https://github.com/actions/runner-images/issues/11101
As `ubuntu-latest` image does not include `clang-format-11` anymore, the proposal is to move the image to `ubuntu-22.04` and then later update `clang-format` to a newer version and move the image to `ubuntu-latest`.

Update Ubuntu image used for clang-format runs

---

.github/workflows/ODBC.yml
.github/workflows/Vendor.yml

`Vendor.yml` workflow can be called from the mainline `NotifyExternalRepository.yml` workflow on the `main` branch or on one of stable branches like `v1.2-histionicus`. `Vendor.yml` is called with cURL call that triggers `workflow_dispatch` event in which the branch name is a mandatory parameter. It is available to workflow in `github.ref_name` context variable.
This change updates the check for changed engine files to be performed on a correct branch instead of a hardcoded `main`.
It also adds the target branch suffix to `vendoring` branch that is used for vendoring PRs.

Support Vendor.yml workflow for stable branches

---

src/api_info.cpp
src/common/odbc_fetch.cpp
src/common/odbc_interval.cpp
src/connect/connection.cpp
src/descriptor.cpp
src/parameter_descriptor.cpp
src/statement/statement.cpp
src/statement/statement_functions.cpp

This change is moved out from #118 PR.
There are a few warnings about integer narrowing in the codebase. These warning produce a lot of output on Windows and make it easy to miss actually important warnings from new changes.
This change added explicit static casts for integers narrowing.
Testing: no functional changes, no new tests.

Clean up narrowing warnings

---

src/connect/connect.cpp
test/CMakeLists.txt
test/tests/catalog_functions.cpp
test/tests/col_attribute/char_query.cpp
test/tests/col_attribute/uuid_query.cpp
test/tests/test_allowed_paths.cpp
test/tests/test_widechar_conv.cpp

Currently options `allowed_paths` and `allowed_directories` require to have an initialized FS instance attached to the DB config. Otherwise the process of checking file separators in the option value fails with `Attempted to dereference unique_ptr that is NULL`.
This is tracked in the engine in duckdb/duckdb#17128 and is likely to be fixed soon, but meanwhile it is proposed to add the fix to ODBC to not crash the host process when one of these options is set in DSN config.
Additionally the logic added to set `enable_external_access` option after all other options (otherwise path-related options are not allowed to be set) and to handle backslashes in windows paths in path-related options.
Testing: new test added that checks that files can/cannot be read when `allowed_paths` and …

Fix the crash on allowed_paths config option

---

.github/workflows/ODBC.yml
.github/workflows/Vendor.yml

This change should fix the check in "Merge vendoring PR" job where the branch name should be taken not from `github.ref_name` (that has the value like `42/merge` where 42 is a PR number), but from `github.base_ref` that contains the branch name on `pull_request` events.
Additionally a few unneded checks are removed from `Vendor.yml`.
Testing: debugged this in JDBC repo

Fix workflow job that merges vendoring PRs

---

.github/workflows/Vendor.yml

This change improves the check in the DuckDB engine sources vendoring process. If no changes are detected in the incoming sources then the remaining of the Vendor.yml job is skipped instead of moving it to "Failure" state.
Testing: this logic was debugged in duckdb/duckdb-java#220.

Do not fail Vendor.yml when no changes imported

---

.github/workflows/ODBC.yml
.gitignore
include/api_info.hpp
scripts/format.py
src/api_info.cpp
src/common/odbc_utils.cpp
test/tests/dotnet-linux/Program.cs
test/tests/dotnet-linux/README.md
test/tests/dotnet-linux/dotnet.csproj

This PR correct the type mapping changing the ODBC type to `SQL_DECIMAL` for the following DuckDB types:
- `UBIGINT`
- `HUGEINT`
- `UHUGEINT`
- `DECIMAL`
.NET CLS type for these DB types is now `System.Decimal`.
Testing: new test-suite is added using `dotnet` on Linux. Currently it only covers the type mapping from `OdbcConnection` to .NET CLS types. It overlaps with existing Windows `dotnet` test-suite, but it appeared challenging to iterate over Windows `dotnet` due to long compile times on Windows. New test-suite is confirmed to work on Ubuntu-22.04 and Fedora. It is added to `ODBC Tests` CI run.
Fixes: #93

Correct type mappings for .NET numeric types

---

include/odbc_utils.hpp
src/api_info.cpp
src/common/odbc_utils.cpp
src/statement/statement_functions.cpp
test/tests/dotnet-linux/Program.cs
test/tests/test_timestamp.cpp

DuckDB supports `TIMESTAMP WITH TIME ZONE` data type that stores UTC dates (with specified time zone already applied on DB insert). ODBC does not have a notion of time zones. When client app reads such `TIMESTAMP WITH TIME ZONE` it needs to be converted into `TIMESTAMP WITHOUT TIME ZONE` with client-local time zone applied. And such converted timestamp must represent the same moment of time as stored UTC timestamp.
Applying client-local time zone to timestamp is a non-trivial operation
- the UTC offset depends on both the time zone (for fixed shift) and on the timestamp value (for DST shift).
There are two options to get the effective offset for the specified UTC timestamp in the specified time zone:
- DuckDB ICU extension, that will use DB-configured time zone
- OS API, will use …

Support fetching TIMESTAMPTZ as SQL_TYPE_TIMESTAMP

---

include/duckdb_odbc.hpp
test/tests/connect.cpp

I was debugging another issue and stumbled upon this behaviour of `OdbcHandleEnv`: when client app calls `SQLDriverConnect` the Driver Manager allocates the `ENV` handle before calling `SQLDriverConnect` on the driver. When `ENV` handle is allocated - default in-memory instance of DuckDB is initialized. With default settings it creates a number of worker threads (the same as CPU-count). When `SQLDriverConnect` is called immmediately after that - new DB instance is created (with its own set of worker threads) and the default one is destroyed.
This change adds `threads=1` config option to default DB to prevent additional threads creation. It shoult improve startup time a little and should not affect any existing logic.
Testing: new test is added to check that `threads=1` config is not …

Do not create unneeded threads for default DB

---

.github/workflows/ODBC.yml

This change renamed resulting CI artifacts for Linux AArch64 changing `aarch64` label to `arm64`.
Fixes: #135

Rename arm64 artifacts

---

.github/workflows/ODBC.yml
src/statement/statement_functions.cpp
test/CMakeLists.txt
test/pyodbc-test.py
test/tests/test_long_data.cpp

This change implements support for returning variable-length data to client with multiple subsequent calls to `SQLGetData`. The ODBC spec logic for buffer/write/return sizing is relatively straightforward, but there is a number of corner cases. Also the logic for char, widechar and binary data differs slightly (different null-termination handling). This change unifies this logic for all variable-length types in one place.
Testing: new test is added that covers retrieving data by parts for char, widechar and binary data. PyODBC test suite is extended to check the retrieval of overly long strings and also enabled on CI on Windows (to check the retrieval through the Windows Driver Manager).
Fixes: #121

Support retrieving widechar data in parts

---

include/odbc_utils.hpp
src/common/odbc_utils.cpp
src/statement/statement.cpp
test/common.cpp
test/include/odbc_test_common.h
test/tests/catalog_functions.cpp

This change adds support for `CatalogName` parameter in `SQLTables` call that was previously ignored. It is handled the same way as `SchemaName` and `TableName` parameters.
Additionally it fixes special cases in `SQLTables` when only catalogs, schemas or table types are listed.
Testing: existing test is updated to cover catalog filtering and all special cases.
Fixes: #134

Support catalog name in SQLTables

---

.github/workflows/ODBC.yml

This is a backport of the PR #151 to `v1.3-ossivalis` stable branch.
Nightly import of DuckDB engine sources ("vendoring") is performed by creating PRs on `vendoring-<branch>` base branches. After the tests are passed the PR is merged and `vendoring-<branch>` is re-created to be used in subsequent imports.
This change fixes the vendoring branch re-creation to place it not always on the `main` branch, but on the correct branch (either `main` or stable one line `v1.3-ossivalis`).

Fix vendoring PRs for stable branches (1.3)

---

.github/workflows/ODBC.yml

Vendoring (engine source import) PRs are merged automatically after tests are passed for all platforms.
This change fixes the oversight where macOS tests were ignored in checks for merging vendoring PRs.

Enable macOS check for vendoring PR merge

---

.github/workflows/ODBC.yml

This is a backport of the PR #153 to `v1.3-ossivalis` stable branch.
Vendoring (engine source import) PRs are merged automatically after tests are passed for all platforms.
This change fixes the oversight where macOS tests were ignored in checks for merging vendoring PRs.

Enable macOS check for vendoring PR merge (1.3)

---

.github/workflows/ODBC.yml
test/tests/dotnet/CMakeLists.txt

This is a backport of the PR #143 to `v1.3-ossivalis` stable branch.
Windows runnner images are changed from `windows-2019` to `windows-latest` due to actions/runner-images#12045.
Use of .NET SDK 4.7.2 in tests was added before for `windows-2019`, so this bit is removed too.

Update GH Windows runners (1.3)

---

include/odbc_utils.hpp
src/common/odbc_utils.cpp
src/statement/statement.cpp
test/common.cpp
test/include/odbc_test_common.h
test/tests/catalog_functions.cpp

This is a backport of the PR #140 to `v1.3-ossivalis` stable branch.
This change adds support for `CatalogName` parameter in `SQLTables` call that was previously ignored. It is handled the same way as `SchemaName` and `TableName` parameters.
Additionally it fixes special cases in `SQLTables` when only catalogs, schemas or table types are listed.
Testing: existing test is updated to cover catalog filtering and all special cases.
Fixes: #134

Support catalog name in SQLTables (1.3)

---

include/connect.hpp
include/file_io.hpp
include/odbc_utils.hpp
include/session_init.hpp
src/common/CMakeLists.txt
src/common/file_io.cpp
src/common/odbc_utils.cpp
src/connect/CMakeLists.txt
src/connect/connect.cpp
src/connect/session_init.cpp
test/CMakeLists.txt
test/common.cpp
test/include/odbc_test_common.h
test/include/temp_directory.hpp
test/temp_directory.cpp
test/tests/basic_usage.cpp
test/tests/test_connect.cpp
test/tests/test_session_init.cpp
third_party/picosha2.h

This change is a counterpart of a similar functionality in DuckDB JDBC driver added in duckdb/duckdb-java#252.
It adds support for `session_init_sql_file` connection option, that allows to speficy the path to an SQL file in local file system, that will be read by the driver and executed in a newly created connection before passing it to user.
By default the file is initalized only once per database, on the first `SQLConnect` call to this DB.
For `:memory:` connection-private DBs it effectively executed once per connection.
In addition to the DB init, it supports executing a part of the SQL file for every connection. It looks for the specific marker:
```
/* DUCKDB_CONNECTION_INIT_BELOW_MARKER */
```
in the SQL file. If this marker is present - everything before the marker is executed on DB …

Support running an SQL file on init

---

include/connect.hpp
include/file_io.hpp
include/odbc_utils.hpp
include/session_init.hpp
src/common/CMakeLists.txt
src/common/file_io.cpp
src/common/odbc_utils.cpp
src/connect/CMakeLists.txt
src/connect/connect.cpp
src/connect/session_init.cpp
test/CMakeLists.txt
test/common.cpp
test/include/odbc_test_common.h
test/include/temp_directory.hpp
test/temp_directory.cpp
test/tests/basic_usage.cpp
test/tests/test_connect.cpp
test/tests/test_session_init.cpp
third_party/picosha2.h

This is a backport of the PR #157 to `v1.3-ossivalis` stable branch.
This change is a counterpart of a similar functionality in DuckDB JDBC driver added in duckdb/duckdb-java#252.
It adds support for `session_init_sql_file` connection option, that allows to speficy the path to an SQL file in local file system, that will be read by the driver and executed in a newly created connection before passing it to user.
By default the file is initalized only once per database, on the first `SQLConnect` call to this DB.
For `:memory:` connection-private DBs it effectively executed once per connection.
In addition to the DB init, it supports executing a part of the SQL file for every connection. It looks for the specific marker:
```
/* DUCKDB_CONNECTION_INIT_BELOW_MARKER */
```
in the SQL file. If …

Support running an SQL file on init (1.3)

---

src/parameter_descriptor.cpp
src/statement/statement_functions.cpp
test/tests/numeric.cpp

Fixes a bug where negative decimal values were not properly handled when using SQL_NUMERIC_STRUCT parameters and results.
**Issue**
The ODBC driver ignored the sign field in SQL_NUMERIC_STRUCT, causing negative decimal values to be treated as positive. Per ODBC spec: sign = 0 means negative,
sign = 1 means positive.
**Changes**
- Parameter handling: Now applies negation when numeric->sign == 0 for both int64_t and hugeint_t paths
- Result processing: Added exception handling for std::stoi() edge cases and simplified hugeint_t conversion
- Tests: Added negative decimal test cases

Fix SQL_NUMERIC_STRUCT handling for negative decimals

---

.github/workflows/ODBC.yml
CMakeLists.txt
CMakeLists.txt.in
src/CMakeLists.txt
src/common/CMakeLists.txt
src/connect/CMakeLists.txt
src/statement/CMakeLists.txt
src/widechar/CMakeLists.txt
test/CMakeLists.txt

This change adds `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` flag for Windows builds that prevents crashes when the host process, into which the ODBC driver is loaded, is run using older versions of C++ stdlib.
Details: duckdb/duckdb#17991
Testing: additional test run added that uses `msvcp140.dll` from VS2019 instead of the system-provided one.

Support running with older C++ stdlib

---

.github/workflows/ODBC.yml
CMakeLists.txt
CMakeLists.txt.in
src/CMakeLists.txt
src/common/CMakeLists.txt
src/connect/CMakeLists.txt
src/statement/CMakeLists.txt
src/widechar/CMakeLists.txt
test/CMakeLists.txt

This is a backport of the PR #169 to `v1.3-ossivalis` stable branch.
This change adds `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` flag for Windows builds that prevents crashes when the host process, into which the ODBC driver is loaded, is run using older versions of C++ stdlib.
Details: duckdb/duckdb#17991
Testing: additional test run added that uses `msvcp140.dll` from VS2019 instead of the system-provided one.

Support running with older C++ stdlib (1.3)

---

include/api_info.hpp
src/api_info.cpp
src/common/duckdb_odbc.cpp
src/descriptor.cpp
src/prepared.cpp
test/CMakeLists.txt
test/common.cpp
test/include/odbc_test_common.h
test/tests/alter.cpp
test/tests/bools_as_char.cpp
test/tests/catalog_functions.cpp
test/tests/col_attribute/decimal_query.cpp
test/tests/col_attribute/temporal_query.cpp
test/tests/col_attribute/unsigned_int_query.cpp
test/tests/multicolumn_param_bind.cpp

This is a backport of the PR #177 to `v1.3-ossivalis` stable branch.
This change addresses multiple ODBC specification conformance issues discovered during a thorough audit of GetColumnSize() and GetDisplaySize() implementations.
Issues fixed:
1. DECIMAL/NUMERIC precision and scale reporting
- SQLColAttribute/SQLDescribeCol incorrectly reported column sizes
- Fixed GetColumnSize() to return precision instead of precision+scale
2. Signed/Unsigned integer display sizes
- GetDisplaySize() now correctly distinguishes signed vs unsigned types
- UTINYINT: 3 chars, USMALLINT: 5 chars, UINTEGER: 10 chars, UBIGINT: 20 chars
- TINYINT: 4 chars, SMALLINT: 6 chars, INTEGER: 11 chars, BIGINT: 20 chars
3. TIME/TIMESTAMP fractional seconds precision
- Added GetTemporalPrecision() to detect precision …

Fix ODBC conformance for numeric types (1.3)

---

src/duckdb/src/function/table/version/pragma_version.cpp

Changes:
- [duckdb/duckdb#2efc9ec537](https://github.com/duckdb/duckdb/commit/2efc9ec537) imported at 2025-07-30 05:41:14

Update vendored DuckDB sources to 2efc9ec537

---

src/duckdb/src/function/table/version/pragma_version.cpp

Changes:
- [duckdb/duckdb#c5310ec83b](https://github.com/duckdb/duckdb/commit/c5310ec83b) imported at 2025-08-22 06:58:39

Update vendored DuckDB sources to c5310ec83b

---

.github/workflows/ODBC.yml

This change revert the usage of `gcc-toolset-12` for `x86_64` and `aarch64` Linux builds. See duckdb/duckdb#17963 for details.

Revert GCC 12 downgrade for Linux builds

---

src/duckdb/src/function/table/version/pragma_version.cpp

Changes:
- [duckdb/duckdb#40e7271486](https://github.com/duckdb/duckdb/commit/40e7271486) imported at 2025-09-04 05:33:23

Update vendored DuckDB sources to 40e7271486

---

src/duckdb/src/function/table/version/pragma_version.cpp

Changes:
- [duckdb/duckdb#b8a06e4a22](https://github.com/duckdb/duckdb/commit/b8a06e4a22) imported at 2025-09-16 19:31:09

Update vendored DuckDB sources to b8a06e4a22

---

src/prepared.cpp
test/CMakeLists.txt
test/tests/test_num_result_cols.cpp

This is a backport of the PR #241 to `v1.4-andium` stable branch.
This PR fixes the `SQLNumResultCols` function making it to return the actual number of columns for `CALL`, `EXECUTE` and `EXPLAIN` queries. Without that some ODBC clients were unable to fetch the result set for such queries.
`EXPLAIN` output contains 1 row with 2 columns. First column is a constant `physical_plan` (or `logical_plan`) and the second column contains actual plan details as a `VARCHAR`.
Testing: new test added.
Fixes: #200

Fix SQLNumResultCols for CALL, EXECUTE (1.4)

---

src/duckdb/src/function/table/version/pragma_version.cpp

Changes:
- [duckdb/duckdb#b3c8acdc0e](https://github.com/duckdb/duckdb/commit/b3c8acdc0e) imported at 2025-10-07 03:30:35

Update vendored DuckDB sources to b3c8acdc0e
